name: Build and Test

# Trigger this workflow on push or pull request to main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: github-actions/setup-cmake@v1
      with:
        cmake-version: '3.21'

    - name: Build with CMake
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Run tests
      run: |
        cd build
        ctest
