name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: actions/setup-cmake@v2

      - name: Install dependencies
        run: sudo apt-get install build-essential

      - name: Configure CMake
        run: cmake .

      - name: Build project
        run: make

      - name: Run tests
        run: ./tests/your_test_binary
