name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up CMake
    - name: Set up CMake
      uses: cmake/setup-cmake@v3
      with:
        cmake-version: '3.21'

    # Create a build directory
    - name: Create build directory
      run: mkdir build && cd build

    # Configure with CMake
    - name: Configure with CMake
      run: cmake ..

    # Build with CMake
    - name: Build with CMake
      run: cmake --build .

    # Run tests
    - name: Run tests
      run: ctest --output-on-failure
